name: data-science-notebook
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib